#!/bin/bash

args=("$@")

if [ ${#args[@]} -eq 1 ]; then
  many_args=1
fi

s="$1"
shift

fs=$(grep -l -R -w "$s" .)

for s in "$@"; do
  fs=$(echo "$fs" | \
    while read filename; do
      grep -w -l "$s" $filename;
    done)
done

echo

for f in `echo "$fs"`; do
  echo "## ${f}"
  for s in "${args[@]}"; do
    [ -z "$many_args" ] && echo "- ${s} -"
    grep -n --colour "$s" "$f"
  done
  echo
done
