#!/bin/bash

args=$@

string1=$1
shift

fs=$(grep -l -R -w $string1 .)

for s in "$@"; do
  fs=$(echo "$fs" | \
    while read filename; do
      grep -w -l "$s" $filename;
    done)
done

#echo "$fs" # do this with -l

for f in $(echo "$fs"); do
  echo "${f}:"
  for a in $(echo "$args"); do
    grep -n --colour "$a" "$f"
  done
  echo
done
